---
output: stevetemplates::cv
geometry: margin=1in

title: "CV"
author: Eric Daniel Youngerman

jobtitle: "Research Support Specialist, Sustainable Cropping Systems Lab"
address: "Cornell University · 515 Bradfield Hall · Ithaca NY, 14850"
fontawesome: yes
email: ey239@cornell.edu
# github: svmiller
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
phone: "781 759 9629"
web: blogs.cornell.edu/scslab
updated: TRUE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Employment

*Cornell University, Sustainable Cropping Systems Lab*

Research support specialist \hfill 2021-present

*Snowplace Farm*

Farm assistant \hfill 2018-2021

*University of Utah, Longino Lab*

Graduate research assistant \hfill 2014-2015

*University of Toronto, Frederickson Lab*

Graduate research assistant \hfill 2012-2014

*Harvard University, Museum of Comparative Zoology, Ant Collection*

Collections assistant \hfill 2012

*New Guinea Binatang Research Center, Madang, Papua New Guinea       *

Research assistant \hfill 2011-2012

*Harvard University, Lauder Laboratory*

Research assistant \hfill 2010-2011

*Harvard University, Arnold Arboretum*

Curatorial assistant \hfill 2007-2009

# Education
*Cornell University*, PhD \hfill Expected 2030

*Harvard University Extension School*, ALB \hfill 


# Publications

## Journal Articles

Huddell, A. M., Thapa, R., Marcillo, G. S., Abendroth, L. J., Ackroyd, V. J., Armstrong, S. D., ... & Mirsky, S. B. (2024). "US cereal rye winter cover crop growth database." *Scientific Data*, 11(1), 200.

Malé, P. J. G., **Youngerman, E.**, Pierce, N. E., & Frederickson, M. E.  2020. "Mating system, population	genetics, and phylogeography of the devil’s garden ant, Myrmelachista schumanni, in the	Peruvian Amazon." *Insectes Sociaux* 67(1), 113-125.

Janda, M., Matos-Maraví, P., Borovanska, M., Zima, J., **Youngerman, E.**, & Pierce, N. E.  2016. "Phylogeny and population genetic structure of the ant genus Acropyga (Hymenoptera:	Formicidae) in Papua New Guinea. " *Invertebrate Systematics* 30(1), 28-40.

Cembrowski, A. R., Reurink, G., Arcila Hernandez, L. M., Sanders, J. G., **Youngerman, E.**, & Frederickson, M. E. 2015. "Sporadic pollen consumption among tropical ants." *Insectes sociaux* 62, 379-382.

**Youngerman, E. D.**, Flammang, B. E., & Lauder, G. V. 2014. "Locomotion of free-swimming ghost knifefish: anal fin kinematics during four behaviors." *Zoology* 117(5), 337-348


# Oral Presentations

**Youngerman, E.D.**, Pelzer, C., Loria, K., Mallory, E.B., Darby, H., Silva, E.M. & Ryan, M. 2024. Interrow	Mowing	in	Organic	No-Till	Planted	Dry	Bean. European Weed Research Society Physical and Cultural Weed Control Workshop, Wageningen, Netherlands.

**Youngerman, E.**, Pelzer, C., Ryan, M., & Loria, K. 2024. Interrow mowing as a supplemental weed management tool in organic soybean. Musgrave Research Farm Field Day, Cornell University.

**Youngerman, E.**, Pelzer, C., Ryan, M., & Sosnoskie, L. 2023. Impact of timing of cereal rye cover crop termination on pests and diseases in no-till corn. Musgrave Research Farm Field Day, Cornell University.

**Youngerman, E.** 2014. Caste or intercaste? An abundant, morphologically distinct worker of Myrmelachista schumanni in devil’s gardens in the Peruvian Amazon. TGIF Student Seminar
Series, University of Utah.

Malé, Pierre-Jean and **Youngerman, E.** 2014. Evolution and ecology of ant-plant relationships:exploring devil’s gardens. Social Insects in the North East Regions (SINNERS 3), Philadelphia, PA.

**Youngerman, E.** 2012. Ants of the mangroves and mid-lagoon islands of Madang Lagoon. Pacific Ants	Summit, Harvard University, Cambridge, MA.

# Teaching Experience

*Graduate Teaching Assistant, University of Utah*	

Entomology \hfill 2015

*Graduate Teaching Assistant, University of Toronto*	

Adaptation and Evolution \hfill 2012

